# -*- coding: utf-8 -*-
# 升级 listening_cet6.js 六套的英文句子（提高词汇与句式密度，保句数不变）
import io, re

p = r'D:\六级APP\js\data\listening_cet6.js'
t = io.open(p, encoding='utf-8').read()

# 逐套替换（保持句数/顺序/说话人前缀不变，只提升英文表达密度）
REPL = [
# c5 论文选题
("W: Professor Hayes, do you have a minute? I'm stuck on my term paper topic.",
 "W: Professor Hayes, have you got a minute? I've been circling a term-paper topic for two weeks and getting nowhere."),
("M: Of course, Anna. What area were you thinking about?",
 "M: Of course, Anna. Talk me through the ground you've been covering."),
("W: Something about remote work, but everyone is writing about that. It feels overdone.",
 "W: Something on remote work, presumably — except the territory has been thoroughly harvested; every angle I try feels second-hand."),
("M: Then narrow it down. Remote work is a field; a topic is a question.",
 "M: Then the remedy is precision. Remote work is a territory; a topic is a single, answerable question within it."),
("M: For instance, how remote work changes the career chances of new graduates in smaller cities. That is measurable.",
 "M: For instance, whether remote hiring has altered the early-career prospects of graduates in second-tier cities — narrow enough to test, broad enough to matter."),
("W: That's interesting. But would I find enough data?",
 "W: That's compelling. But would the evidence base sustain it?"),
("M: Check the national labor survey and three recent industry reports. They overlap nicely.",
 "M: Anchor it in the national labour survey and three recent industry reports; the figures triangulate nicely."),
("W: Should I interview fresh graduates as well?",
 "W: Should I supplement the statistics with interviews?"),
("M: Five or six short interviews would give your paper a voice. Keep each under ten minutes.",
 "M: Five or six brief interviews would give the argument a human dimension — cap each at ten minutes and code them for recurring themes."),
("M: Proposal by next Friday. If it looks focused, I'll approve it the same day.",
 "M: Proposal by next Friday; if the question is as sharply drawn as it is now, I'll approve it the same day."),
# c6 房租上涨
("M: Did you see the email from the landlord? The rent is going up by fifteen percent in March.",
 "M: Did you see the landlord's email? The rent is being raised by fifteen percent from March — effective overnight, as far as our budget is concerned."),
("W: Fifteen percent? That's more than double the rise last year. Did he give a reason?",
 "W: Fifteen percent? That's more than double what he asked last year. Did he offer any justification?"),
("M: Renovations, apparently. New heating system, new windows, that kind of thing.",
 "M: Renovations, ostensibly — a replaced heating system, upgraded windows, the usual inventory."),
("W: Renovations we never asked for. What are our options?",
 "W: Renovations nobody requested, payable by us. What are our options, realistically?"),
("M: We could accept it, negotiate, or move out when the lease ends in June.",
 "M: We can absorb it, contest it, or vacate when the lease expires in June."),
("W: Moving is expensive. Agents, deposits, a truck... it could eat two months' rent.",
 "W: Moving is ruinous in its own right — agency fees, deposits, a van; it could consume two months' rent."),
("M: True, but fifteen percent is ninety more dollars a month. That's over a thousand a year.",
 "M: Granted, yet fifteen percent means ninety more dollars a month — upwards of a thousand annually."),
("W: Let's try negotiating first. Comparable flats nearby went up by only eight percent.",
 "W: Negotiation first, then. Comparable flats in the neighbourhood rose by only eight percent."),
("M: Good point. We can show him those listings and ask for ten, with a two-year lease.",
 "M: Sound reasoning. We present those listings and press for ten percent, in exchange for a two-year commitment."),
("W: Stability is worth something to him too. He won't need to find new tenants.",
 "W: Continuity benefits him as well — it spares him the vacancy and the search."),
("M: Precisely. I'll draft the email tonight and we send it together?",
 "M: Exactly. I'll draft the counter-proposal tonight and we send it jointly?"),
# p5 数字极简
("A growing number of young professionals now practise what psychologists call digital minimalism.",
 "A growing share of young professionals now practise what psychologists have labelled digital minimalism."),
("It does not mean quitting technology altogether; it means using it with clear intention.",
 "The doctrine does not counsel abandoning technology altogether; it demands that technology be deployed with deliberate intention."),
("Followers of the idea typically delete apps that merely consume attention and keep only a few essential tools.",
 "Adherents typically uninstall the applications engineered to harvest attention and retain only a handful of indispensable tools."),
("In a study at a European business school, sixty volunteers reduced personal screen time to one hour a day for a month.",
 "In a study conducted at a European business school, sixty volunteers capped personal screen time at one hour a day for a month."),
("By the end of the month, two thirds reported better concentration at work.",
 "By the end of the trial, two thirds reported measurably sharper concentration at work."),
("More strikingly, their reported loneliness dropped, although they met no more people offline than before.",
 "More strikingly, their reported loneliness declined — although they met no more people offline than they had before."),
("The researchers suggest that constant low-quality contact online may make people feel more isolated, not less.",
 "The researchers suggest that constant, low-quality contact online may deepen isolation rather than relieve it."),
("Critics point out that the study was small and short.",
 "Critics object that the sample was small and the trial brief."),
("Even so, many companies now run quiet hours, banning internal messages after eight in the evening.",
 "Even so, a number of firms have introduced quiet hours, banning internal messages after eight in the evening."),
("The broader lesson may be simple: attention is a limited resource, and it deserves a budget.",
 "The wider lesson may be disarmingly simple: attention is a finite resource, and it deserves a budget."),
# p6 城市热岛
("Cities are usually several degrees warmer than the countryside that surrounds them.",
 "Cities routinely run several degrees warmer than the countryside encircling them."),
("Scientists call this the urban heat island effect, and it is strongest on summer nights.",
 "Scientists term this the urban heat island effect, and it peaks on summer nights."),
("Dark roofs absorb sunlight all day and release the heat slowly after dark.",
 "Dark roofs absorb sunlight throughout the day and radiate the stored heat slowly after dark."),
("One increasingly popular answer is the green roof, covered with plants and soil.",
 "One increasingly favoured remedy is the green roof, blanketed with vegetation and growing medium."),
("A three-year study in Singapore compared forty buildings with and without green roofs.",
 "A three-year investigation in Singapore compared forty buildings with and without planted roofs."),
("On hot days, rooms below green roofs stayed up to four degrees cooler.",
 "On hot days, rooms beneath green roofs remained up to four degrees cooler."),
("The cooling reduced air-conditioning costs by about twenty percent in those buildings.",
 "The cooling lowered air-conditioning expenditure in those buildings by roughly twenty percent."),
("Some cities now offer subsidies covering half the cost of installing a green roof.",
 "Several municipalities now underwrite half the cost of installing a green roof."),
("Farmers have gone one step further, growing vegetables on the roofs of supermarkets.",
 "Growers have proceeded a step further, cultivating vegetables on supermarket rooftops."),
("Produce grown upstairs travels meters instead of kilometers, cutting transport costs and emissions.",
 "Produce harvested overhead travels metres rather than kilometres, trimming both transport costs and emissions."),
# l1 测试效应
("Good afternoon. Today I want to talk about one of the most reliable findings in learning science: the testing effect.",
 "Good afternoon. Today's lecture concerns one of the most robust findings in the science of learning: the testing effect."),
("Common sense says that we learn best when we study material again and again.",
 "Intuition insists that material is mastered by being read again and again."),
("But a century of experiments suggests the opposite: memory grows strongest when we try to pull information out of our heads.",
 "Yet a century of experimentation indicates otherwise: memory consolidates when we are made to retrieve information from memory itself."),
("Psychologists call this retrieval practice, or the act of remembering as training.",
 "Psychologists call this retrieval practice — the act of remembering recast as training."),
("In a classic experiment, two groups of students read the same scientific text.",
 "In a canonical experiment, two matched groups of students read an identical scientific passage."),
("One group read the passage four times; the other read it once and then took a practice test.",
 "One group reread the passage four times; the other read it once and then sat a test on it."),
("A week later, the testing group remembered about fifty percent more than the rereading group.",
 "A week later, the testing group outperformed the rereaders by roughly fifty percent on recall."),
("Why does pulling information out work so well? Think of memory as a path through a forest.",
 "Why does retrieval work so well? Picture memory as a footpath across dense forest."),
("Walking a path again makes it clearer; rereading is like standing at the edge and looking at the map.",
 "Walking the path again tramples it clear; rereading amounts to standing at the treeline consulting the map."),
("Retrieval also reveals gaps that rereading hides, because recognizing a fact is not the same as producing it.",
 "Retrieval also exposes the gaps that rereading conceals, since recognising a fact is not the same as producing one."),
("So how should students use this? Turn every chapter into questions, and answer them from memory first.",
 "How, then, should students apply this? Convert every chapter into questions and answer them from memory first."),
("Check the book only afterwards, and space the attempts over days, not hours.",
 "Consult the text only afterwards, and space the attempts across days rather than hours."),
("however uncomfortable, the struggle to recall is precisely the moment memory strengthens.",
 "However uncomfortable, the struggle to recall is precisely the moment at which memory strengthens."),
# l2 定价心理学
("Welcome back to our economics lecture series. Today's topic is the psychology of pricing.",
 "Welcome back to the economics lecture series. Today we turn to the psychology of pricing."),
("Classical theory assumes buyers compare prices rationally and pick the cheapest option that meets their needs.",
 "Classical theory presumes that buyers weigh prices rationally and select the least expensive option that satisfies their needs."),
("Real buyers rarely behave that way, and sellers know it.",
 "Actual purchasers seldom behave so, and sellers are keenly aware of it."),
("Consider the common three-tier menu: a basic plan, a standard plan, and a premium plan.",
 "Consider the ubiquitous three-tier menu: a basic plan, a standard plan and a premium plan."),
("Most customers avoid both extremes and choose the middle option.",
 "Most customers shun both extremes and settle on the middle option."),
("Businesses understand this, so the premium tier often exists mainly to make the middle one look reasonable.",
 "Firms understand this; hence the premium tier frequently exists chiefly to lend the middle one an air of reasonableness."),
("Another trick is charm pricing: cutting the price from ten dollars to nine ninety-nine.",
 "A second device is charm pricing: shaving the tag from ten dollars to nine ninety-nine."),
("Experiments show the one-cent cut can lift sales noticeably, because nine-something feels meaningfully cheaper than ten.",
 "Experiments indicate that the one-cent reduction measurably lifts sales, because nine-something registers as meaningfully cheaper than ten."),
("Stores also use anchor prices: a jacket first shown at two hundred dollars seems a bargain at one hundred twenty.",
 "Retailers also deploy anchor prices: a jacket first displayed at two hundred dollars appears a bargain at one hundred twenty."),
("Is any of this manipulation? Regulators draw the line at false reference prices.",
 "Does any of this constitute manipulation? Regulators draw the line at fabricated reference prices."),
("Showing a fake original price to create a discount illusion is illegal in many countries.",
 "Inventing a fictitious original price to manufacture the illusion of a discount is unlawful in many jurisdictions."),
("For consumers, the defense is simple: decide what the product is worth to you before you look at any price tag.",
 "For consumers the defence is straightforward: decide what a product is worth to you before reading any price tag."),
]

count = 0
for old, new in REPL:
    if old in t:
        t = t.replace(old, new, 1)
        count += 1
    else:
        print('NOT FOUND:', old[:60])

io.open(p, 'w', encoding='utf-8').write(t)
print('replaced:', count, '/', len(REPL))
